HH-69318 create custom runner, move reporters
hhru/gulp-qunit-runner pull request #7
Opened 2017-06-01 17:09 UTC by sintell

- теперь все тесты запускаются на одном инстансе фантома, вместо того, что бы спавнить инстанс на каждый сьют
- Создал кастомный ранер, для тестов под фантомом
- Перенес в репозиторий console reporter и  file reporter

2017-06-02 10:12 UTC, tp4k commented on gulp-qunit-runner.js
> +var spawn = require('child_process').spawn;
Это кажется не нужно.

2017-06-02 10:14 UTC, sintell commented on gulp-qunit-runner.js
> +var spawn = require('child_process').spawn;
а этого тут уже и нет) ты забыл страничку обновить

2017-06-02 10:19 UTC, tp4k commented on runner.js
>      'use strict';
У нас ес6, можно это везде не писать.

2017-06-02 10:27 UTC, tp4k commented on runner.js
> +        require("system").stderr.write(Array.prototype.join.call(arguments, ' ') + '\n');
Хорошим тоном считается риквайрить в начале файла.

2017-06-02 10:31 UTC, tp4k commented on runner.js
> +                        text += '\t' + currentTestAssertions[i];
Удобнее будет читать если сделать `\n` вместо `\t`

2017-06-02 10:39 UTC, tp4k commented on consoleReport.js
> +    if (result) {
Переменные выше надо создавать только если result есть. Да и везде лишний отступ. Тут кажется лучше в начале !result return

2017-06-02 10:40 UTC, tp4k commented on consoleReport.js
> +    var passed = true;
Переменная не нужна.

2017-06-02 10:42 UTC, tp4k commented on .gitignore
> +.DS_Store
nl

2017-06-02 10:52 UTC, tp4k commented on gulp-qunit-runner.js
> +            emitter.emit('close');
Почему close только если ошибок нет?

2017-06-02 10:58 UTC, tp4k commented on runner.js
> +                        response += ', ';
Мне кажется лучше выше тернарник написать - при инициализации response

2017-06-02 10:59 UTC, tp4k commented on runner.js
> +            timeout = 5;
Почему решил тут таймаут в 5 в итоге оставить?

2017-06-02 11:01 UTC, tp4k commented on runner.js
> +            if (message.name === 'QUnit.done') {
Давай лучше склеим 2 ифа.

2017-06-02 11:45 UTC, xnimorz commented on consoleReport.js
> +            if (result.indexOf('{') !== -1) {
=== 0?

2017-06-02 11:45 UTC, xnimorz commented on consoleReport.js
> +var chalk = require('chalk');
const всякие и прочее, неэ?

2017-06-02 11:45 UTC, xnimorz commented on consoleReport.js
> +                    gutil.log('gulp-qunit: ' + chalk.red('✖ ') + 'QUnit assertions failed in ' + chalk.blue(out.file));
темплатес стрингс

2017-06-02 11:58 UTC, xnimorz commented on runner.js
> +})();
по логике норм, поправить бы стили и остальные места подобные

2017-06-02 15:40 UTC, sintell commented on runner.js
>      'use strict';
нет, эта штука запускается не из под ноды, а внутри фантома, у него свои предпочтения по этому поводу

2017-06-02 16:44 UTC, sintell commented on runner.js
> +            timeout = 5;
он будет тут по умолчанию, но можно переопределить сверху

2017-06-02 16:44 UTC, sintell commented on runner.js
> +})();
поправил

2017-06-05 09:15 UTC, xnimorz requested changes

2017-06-05 09:15 UTC, xnimorz commented on consoleReport.js
> +    if (!result || result.indexOf('{') !== 0) {
Result.includes?)))

2017-06-05 09:15 UTC, xnimorz commented on fileReport.js
> +            {
Лишний блочный скоуп. Или ты упустил какую-то конструкцию

2017-06-05 09:15 UTC, xnimorz commented on fileReport.js
> +            fs.writeFileSync(`qunit-report-${out.file}.json`, JSON.stringify(out.data), 'utf8');
Можно стригифай форматным ещё сделать, чтобы читать файл можно было если что. Это как предложение, не более))

2017-06-05 09:15 UTC, xnimorz commented on runner.js
> +    var args = system.args;
Не очень круто, что в одном пакете у тебя и es5 и es6 смешались в кучу(((

2017-06-05 09:15 UTC, xnimorz commented on runner.js
> +            timeout = 5;
Давай в константы значения, а то мало, что магия, так ещё и вычисления там висят. Плюс этот файл нужно, как и остальные перевести на es6

2017-06-05 09:46 UTC, sintell commented on runner.js
> +    var args = system.args;
я добавлю коммент в runner  -- почему так

2017-06-05 09:59 UTC, sintell commented on consoleReport.js
> +    if (!result || result.indexOf('{') !== 0) {
ага

2017-06-05 09:59 UTC, sintell commented on fileReport.js
> +            {
переносил условие выше, случайно забыл

2017-06-05 10:00 UTC, sintell commented on fileReport.js
> +            fs.writeFileSync(`qunit-report-${out.file}.json`, JSON.stringify(out.data), 'utf8');
сделал, пусть будет удобнее

2017-06-05 10:00 UTC, sintell commented on runner.js
> +    var args = system.args;
добавил комент, в кратце: runner.js запускается внутренним движком phantomjs и он не поддерживает es6
Могу остальные файлы вернуть на es5

2017-06-07 06:59 UTC, xnimorz approved these changes

2017-06-07 08:15 UTC, tp4k commented on gulp-qunit-runner.js
> +    const options = params || {};
Мы вроде не меняем options, давай через дефолт парамс сделаем, модно молодежно.

2017-06-07 08:18 UTC, tp4k commented on gulp-qunit-runner.js
> +    childArgs.push(require.resolve('./runner'));
Риквайрить выше красивше.

2017-06-07 08:18 UTC, AndreyGladkov commented on gulp-qunit-runner.js
> +    const options = params || {};
я бы вообще избавился от options, юзал бы просто params

2017-06-07 08:22 UTC, tp4k approved these changes

2017-06-07 09:36 UTC, sintell commented on gulp-qunit-runner.js
> +    childArgs.push(require.resolve('./runner'));
сделал

2017-06-07 09:36 UTC, sintell commented on gulp-qunit-runner.js
> +    const options = params || {};
сделал

2017-06-07 09:40 UTC, sintell commented
Поправил и заамендил

2017-06-07 10:57 UTC, merged